name: mero_bazar
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8

  provider: any
  image_picker: ^1.0.7
  
  # Local Database (Offline Storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.9.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  test_cov_console: ^0.2.2
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/crops/cereals/
    - assets/crops/fruits/
    - assets/crops/vegetables/


    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: lato Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf

    - family: lato Italic
      fonts:
        - asset: assets/fonts/Lato-Italic.ttf

    - family: lato BoldItalic
      fonts:
        - asset: assets/fonts/Lato-BoldItalic.ttf
    - family: lato Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
